package com.hcl.ecommerce.Ecomerce.Controller.Email;

import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Properties;

public class SendEmail{
    public static void sendEmail(String toAddress, String message, String header){

        String host = "smtp.mailtrap.io";
        final String username = "2edbbf6e9b39ef";//username generated by Mailtrap
        final String password = "e309978828cf70";

        // sets SMTP server properties
        Properties properties = new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", "2525");





        // creates a new session with an authenticator
        Session session = Session.getInstance(properties,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });

                    try {
                        // Create a default MimeMessage object.
                        Message msg = new MimeMessage(session);

                        // Set From: header field
                        msg.setFrom(new InternetAddress("EvolveAdmin@evolve.com"));

                        // Set To: header field
                        msg.setRecipients(Message.RecipientType.TO,
                                InternetAddress.parse(toAddress));

                        // Set Subject: header field
                        msg.setSubject(header);

                        // Put the content of your message
                        msg.setText(message);

                        // Send message
                        Transport.send(msg);

                        System.out.println("Sent message successfully....");

                    } catch (MessagingException e)

                    {
                        throw new RuntimeException(e);
                    }
    }
}